on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        

      - name: Create Release Archive
        run: |
          
          # Copy all files except the excluded ones
          find . -type f | grep -Ev "exclude_file\.txt" | zip -@ release-$(date +'%Y%m%d%H%M%S').zip

      - name: Upload Release Artifact
        uses: actions/upload-artifact@v2
        with:
          name: release-archive
          path: release-$(date +'%Y%m%d%H%M%S').zip