
name: Create Release Archive

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Get Tag Name
        id: tag
        run: echo ::set-output name=tag_name::${GITHUB_REF#refs/tags/}

      - name: Create Release Archive
        run: |
          VERSION=${{ steps.tag.outputs.tag_name }}
          # Copy all files except the excluded ones
          find . -type f | grep -Ev "exclude_file\.txt" | zip -@ release-${VERSION}.zip

      - name: Upload Release Artifact
        uses: actions/upload-artifact@v2
        with:
          name: release-archive
          path: release-${{ steps.tag.outputs.tag_name }}.zip