name: Release Artifacts

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest  # Latest available Ubuntu runner

    steps:
      - uses: actions/checkout@v3  # Latest version of checkout action

      - name: Set up Node.js
        uses: actions/setup-node@v3  # Latest version of setup-node action
        with:
          node-version: '18'  # Using the latest stable Node.js version (v18)

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Package release artifacts
        id: package
        run: |
          # Whitelisted files to include in the release artifacts
          WHITELIST="file1.txt file2.js"

          # Blacklisted files to exclude from the release artifacts
          BLACKLIST="file3.txt file4.js"

          # Create a zip archive with whitelist files
          zip -r release-artifacts.zip $WHITELIST

      - name: Upload release artifact
        uses: actions/upload-artifact@v3  # Latest version of upload-artifact action
        with:
          name: release-artifacts
          path: release-artifacts.zip
