name: Create Release Artifact

on:
  push:
    branches:
      - main

jobs:
  create_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code from your repository
        uses: actions/checkout@v4
        with:
          repository: 'JadianRadiator/RF5-NPC-Checklist'  # Replace with your repository's owner and name

      - name: Set up Node.js (adjusted to use node20)
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # Change to node20 to avoid deprecation

      - name: Install dependencies
        run: npm install

      - name: Create zip archive
        run: |
          # Define blacklist items
          # BLACKLIST=("file1.txt" "folder2")

          # Create archive excluding items in the blacklist
          zip -r release-${GITHUB_SHA::8}.zip . -x "${BLACKLIST[@]}"
      
      - name: Upload release artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-${GITHUB_SHA::8}
          path: release-${GITHUB_SHA::8}.zip
