name: Generate Short Hash and Create Release

on:
  push:
    branches:
      - main  # Change this to your desired branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check for Skip Release Tag
        id: check_skip_release
        run: |
          SKIP_RELEASE=$(git log -1 --format='%B' | grep -i 'skip-release')
          if [ -z "$SKIP_RELEASE" ]; then
            echo "SKIP_RELEASE=false" >> $GITHUB_ENV
          else
            echo "SKIP_RELEASE=true" >> $GITHUB_ENV
          fi

      - name: Generate Short Hash (Conditional)
        id: generate_short_hash
        if: ${{ env.SKIP_RELEASE == 'false' }}
        run: |
          # Get the current timestamp
          TIMESTAMP=$(date +"%H_%M_%S")
          echo "Timestamp: $TIMESTAMP"
          echo "timestamp=$TIMESTAMP" >> $GITHUB_ENV  # Store in environment variable

          # Encode the timestamp to Base64 and truncate it to 4 characters
          SHORT_HASH=$(echo -n "$TIMESTAMP" | base64 | cut -c1-4)
          echo "Short Hash: $SHORT_HASH"
          echo "short_hash=$SHORT_HASH" >> $GITHUB_ENV  # Store short hash in environment variable

      - name: Create Release Version (Conditional)
        id: create_version
        if: ${{ env.SKIP_RELEASE == 'false' }}
        run: |
          # Get the current date components
          MONTH=$(date +'%b')  # 3-letter month (e.g., Oct)
          DAY=$(date +'%d')    # 2-digit day (e.g., 24)
          YEAR=$(date +'%Y')   # 4-digit year (e.g., 2024)

          # Create a version string in the format Month_Day_Year-HASH
          VERSION="${MONTH}_${DAY}_${YEAR}-${{ env.short_hash }}"
          echo "VERSION=$VERSION" >> $GITHUB_ENV  # Store version in environment variable

      - name: Create ZIP file (Conditional)
        id: create_zip
        if: ${{ env.SKIP_RELEASE == 'false' }}
        run: |
          # Get the repository slug
          REPO_SLUG=$(echo "${GITHUB_REPOSITORY}" | cut -d '/' -f 1)

          # Create a ZIP file with the desired naming format
          ZIP_NAME="${REPO_SLUG}-${{ env.short_hash }}.zip"
          zip -r "$ZIP_NAME" . -x ".github/*" ".gitignore" ".git"
          echo "ZIP_NAME=$ZIP_NAME" >> $GITHUB_ENV  # Store ZIP name in environment variable

      - name: Upload Artifact (Conditional)
        id: upload_artifact
        if: ${{ env.SKIP_RELEASE == 'false' }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ZIP_NAME }}  # Use the created ZIP name as the artifact name
          path: ${{ env.ZIP_NAME }}  # Path to the created ZIP file

      - name: Create Release (Conditional)
        id: create_release
        if: ${{ env.SKIP_RELEASE == 'false' }}
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.short_hash }}  # Use only the short hash for the tag
          name: ${{ env.VERSION }}  # Use the created version for the release name
          body: ""  # Empty body as you requested no description
          files: ${{ env.ZIP_NAME }}  # Upload the created ZIP file to the release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use the GITHUB_TOKEN for authentication

      - name: Use Short Hash
        run: |
          echo "The generated short hash is: ${{ env.short_hash }}"`
