name: Generate Short Hash

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate Timestamp
        id: generate_timestamp
        run: |
          # Get the current timestamp in the format hour_minute_second
          TIMESTAMP=$(date +"%H_%M_%S")
          echo "Timestamp: $TIMESTAMP"
          echo "timestamp=$TIMESTAMP" >> $GITHUB_ENV

      - name: Generate Short Hash
        id: generate_short_hash
        run: |
          # Encode the timestamp to Base64 and truncate it to 5 characters
          SHORT_HASH=$(echo -n "$timestamp" | base64 | cut -c1-5)
          echo "Short Hash: $SHORT_HASH"
          echo "short_hash=$SHORT_HASH" >> $GITHUB_ENV

      - name: Use Short Hash
        run: |
          echo "The generated short hash is: ${{ env.short_hash }}"