name: Create Release Artifact

on:
  push:
    branches:
      - main

jobs:
  create_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create zip archive
        run: |
          zip -r release-${GITHUB_SHA::8}.zip . -x "${BLACKLIST[@]}"

      - name: Upload release artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-${GITHUB_SHA::8}
          path: release-${GITHUB_SHA::8}.zip