name: Create Release Artifact

on:
  push:
    branches:
      - main

jobs:
  create_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code from repository
        uses: actions/checkout@v4

      - name: Set up Node.js (adjusted to use node20)
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install
        working-directory: '.'  # Adjust if package.json is in a subdirectory

      - name: Create zip archive
        run: |
          zip -r release-${GITHUB_SHA::8}.zip . -x "${BLACKLIST[@]}"

      - name: Upload release artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-${GITHUB_SHA::8}
          path: release-${GITHUB_SHA::8}.zip