name: Generate Short Hash and Create Release

on:
  push:
    branches:
      - main  # Change this to your desired branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate Timestamp
        id: generate_timestamp
        run: |
          # Get the current timestamp in the format hour_minute_second
          TIMESTAMP=$(date +"%H_%M_%S")
          echo "Timestamp: $TIMESTAMP"
          echo "timestamp=$TIMESTAMP" >> $GITHUB_ENV  # Store in environment variable

      - name: Generate Short Hash
        id: generate_short_hash
        run: |
          # Encode the timestamp to Base64 and truncate it to 4 characters
          SHORT_HASH=$(echo -n "$timestamp" | base64 | cut -c1-4)
          echo "Short Hash: $SHORT_HASH"
          echo "short_hash=$SHORT_HASH" >> $GITHUB_ENV  # Store short hash in environment variable

      - name: Create Release Version
        id: create_version
        run: |
          # Get the current date components
          MONTH=$(date +'%b')  # 3-letter month (e.g., Oct)
          DAY=$(date +'%d')    # 2-digit day (e.g., 24)
          YEAR=$(date +'%Y')   # 4-digit year (e.g., 2024)

          # Create a version string in the format Oct_24_2024-HH_MM_SS
          VERSION="${MONTH}_${DAY}_${YEAR}-${{ env.timestamp }}"
          echo "VERSION=$VERSION" >> $GITHUB_ENV  # Store version in environment variable

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v0.1.${{ env.short_hash }}  # Tag format using the short hash
          release_name: Release ${{ env.VERSION }}  # Release name
          body: |
            This release includes the following features:
            - Feature 1
            - Feature 2
            - Short Hash: ${{ env.short_hash }}  # Include the short hash in the release body
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use the GITHUB_TOKEN for authentication

      - name: Use Short Hash
        run: |
          echo "The generated short hash is: ${{ env.short_hash }}"