on:
  push:
    branches:
      - main  # Adjust to match the branches you want to trigger on

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate minimal timestamp with dashes for version
        id: version
        run: echo "VERSION=$(date +'%y-%m-%d-%H')" >> $GITHUB_ENV  # Generates timestamp (YY-MM-DD-HH)

      - name: Create ZIP file excluding blacklist
        run: |
          zip -r release-${GITHUB_SHA::8}.zip . -x ".github/*" ".gitignore" "RnD*/*"

      - name: List files in workspace
        run: ls -la ${{ github.workspace }}  # List files to verify ZIP location

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-${GITHUB_SHA::8}
          path: ${{ github.workspace }}/release-${GITHUB_SHA::8}.zip  # Ensure correct path is used

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.VERSION }}  # Use the timestamp with dashes as the tag name
          name: Release ${{ env.VERSION }}  # Use the timestamp with dashes as the release name
          files: ${{ github.workspace }}/release-${GITHUB_SHA::8}.zip  # Ensure correct path is used
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Ensure token is provided correctly