on:
  push:
    branches:
      - main  # or your default branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create ZIP file
        run: zip release-${GITHUB_SHA::8}.zip your_files_here

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: release-${GITHUB_SHA::8}
          path: release-${GITHUB_SHA::8}.zip

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v1.0.0
          release_name: Release v1.0.0
          files: release-${GITHUB_SHA::8}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}