on:
  push:
    branches:
      - main  # Adjust to match the branches you want to trigger on

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate minimal timestamp with dashes for version
        id: version
        run: echo "VERSION=$(date +'%y-%m-%d-%H')" >> $GITHUB_ENV  # Generates timestamp (YY-MM-DD-HH)

      - name: Create ZIP file excluding blacklist
        run: |
          zip -r release-${GITHUB_SHA::8}.zip . -x ".github/*" ".gitignore" "RnD*/*"

      - name: List files in workspace
        run: ls -la

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-${GITHUB_SHA::8}
          path: release-${GITHUB_SHA::8}.zip

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.VERSION }}  # Use the timestamp with dashes as the tag name
          name: Release ${{ env.VERSION }}  # Use the timestamp with dashes as the release name
          files: release-${GITHUB_SHA::8}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}