name: Generate Short Hash and Create Release

on:
  push:
    branches:
      - main  # Change this to your desired branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate Short Hash
        id: generate_short_hash
        run: |
          # Get the current timestamp
          TIMESTAMP=$(date +"%H_%M_%S")
          echo "Timestamp: $TIMESTAMP"
          echo "timestamp=$TIMESTAMP" >> $GITHUB_ENV  # Store in environment variable

          # Encode the timestamp to Base64 and truncate it to 4 characters
          SHORT_HASH=$(echo -n "$TIMESTAMP" | base64 | cut -c1-4)
          echo "Short Hash: $SHORT_HASH"
          echo "short_hash=$SHORT_HASH" >> $GITHUB_ENV  # Store short hash in environment variable

      - name: Create Release Version
        id: create_version
        run: |
          # Get the current date components
          MONTH=$(date +'%b')  # 3-letter month (e.g., Oct)
          DAY=$(date +'%d')    # 2-digit day (e.g., 24)
          YEAR=$(date +'%Y')   # 4-digit year (e.g., 2024)

          # Create a version string in the format Month_Day_Year-HASH
          VERSION="${MONTH}_${DAY}_${YEAR}-${{ env.short_hash }}"
          echo "VERSION=$VERSION" >> $GITHUB_ENV  # Store version in environment variable

      - name: Create ZIP file
        run: |
          # Create a ZIP file (adjust the path as needed)
          zip -r "${{ env.VERSION }}.zip" . -x ".github/*" ".gitignore"

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.VERSION }}  # Use the created version as the artifact name
          path: ${{ env.VERSION }}.zip  # Path to the created ZIP file

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.short_hash }}  # Use only the short hash for the tag
          name: ${{ env.VERSION }}  # Use the created version for the release name
          body: ""  # Empty body as you requested no description
          files: ${{ env.VERSION }}.zip  # Upload the created ZIP file to the release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use the GITHUB_TOKEN for authentication

      - name: Use Short Hash
        run: |
          echo "The generated short hash is: ${{ env.short_hash }}"